### ISSUE TITLE
All sentinel-2 items acquired after 13 September 2018 are missing from the sat-api catalog

### ISSUE THREAD

**Issue by carlodef** [sat-utils/sat-api#119]
All sentinel-2 items acquired after 13 September 2018 are missing from the sat-api catalog at https://sat-api/developmentseed.org/search/stac.

This API request:

https://sat-api.developmentseed.org/search/stac?limit=1000&c:id=%22sentinel-2%22&datetime=2018-09-13/2019-01-01

returns no results:

> {"type":"FeatureCollection","properties":{"found":0,"limit":1000,"page":1},"features":[]}

while there are many sentinel-2 images acquired after 2018-09-13 that are available on AWS. For instance this one: https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/30/N/TJ/2018/12/9/0/

@matthewhanson This is the same issue as https://github.com/sat-utils/sat-api/issues/79: it seems that the ingestion of new records stopped when you backfilled the catalog with the missing data on the 13 Sep.

**Comment by matthewhanson** [comment]
@carlodef The upcoming sat-api handles ingestion of data differently and will fix this issue. I'm working on the Sentinel catalog as well, a new version should be up by the end of the year.

**Comment by carlodef** [comment]
@matthewhanson Thanks for your answer. It seems the catalog is still empty for images newer than 13 sep 2018, am I looking at the correct API endpoint?

**Comment by matthewhanson** [comment]
Hello @carlodef sorry this took so long to resolve. 

sat-api has undergone a major refactor and has now been deployed to the our sat-api. It is getting updated in real-time as the Sentinel data gets added to AWS. It does not currently contain the entire historical archive of Sentinel data, as it is still being backfilled, but it should be complete within the next couple weeks.

the API at sat-api.developmentseed.org has been updated to use sat-api 0.2.3 and follows the STAC spec 0.6.0.

STAC endpoint: https://sat-api.developmentseed.org/stac
Search endpoint: https://sat-api.developmentseed.org/stac/search

Querying now works differently, as it follows the STAC spec. See the documentation at:
http://sat-utils.github.io/sat-api/

Also note there is a new version of [sat-search](https://github.com/sat-utils/sat-search/tree/master/satsearch) that works with this new API. The README has info on installing and usage of the CLI, while the new Jupyter notebook is a tutorial on using it as a Python library.
