### ISSUE TITLE
Landsat Pre-Collection Inventory deprecated

### ISSUE THREAD

**Issue by j08lue** [sat-utils/sat-api#12]
It seems like this API is indexing only the Landsat Pre-Collection Inventory, which is [deprecated as of 30th April 2017](https://landsat.usgs.gov/may-10-2017-landsat-4-8-collection-1-processing-complete):

> Effective April 30, 2017, newly-acquired Landsat 7 ETM+ and Landsat 8 OLI/TIRS scenes are being processed into the Landsat Collection 1 inventory only; Landsat Pre-Collection inventory is no longer being populated with newly-acquired data.

A query like the following is not returning any results:

https://api.developmentseed.org/satellites/landsat?search=path:196+AND+row:021+AND+acquisitionDate:2017-05-01+TO+2100-01-01&limit=100
```JSON
{"meta":{"found":0,"name":"sat-api","license":"CC0-1.0","website":"https://api.developmentseed.org/satellites/","page":1,"limit":100},"results":[]}
```

Even though NASA's [EarthExplorer](https://earthexplorer.usgs.gov/) does show data for this query (e.g. 06-MAY-17).

Am I correct here and what can be done about it?

**Comment by vincentsarago** [comment]
@j08lue I opened another ticket here : https://github.com/sat-utils/landsat8-metadata/issues/3

**Comment by j08lue** [comment]
And here, I guess https://github.com/developmentseed/landsat-util/issues/229

**Comment by scisco** [comment]
Version 2.0 uses collection for landsat
