### ISSUE TITLE
Missing Sentinel-2 items prior to January, 2019

### ISSUE THREAD

**Issue by DanSchoppe** [sat-utils/sat-api#169]
When searching for Sentinel-2 scenes by bounding box, most geographic locations return hundreds of results dating back several years. However, I've found a number of geographic locations that seem to be missing Sentinel-2 scenes older than January, 2019. Here's an example request that returns just 12 results, with the earliest being January, 2019. This is just outside of Detroit, MI, USA:
Request
```
curl 'https://sat-api.developmentseed.org/stac/search' \
-H 'Content-Type: text/plain;charset=UTF-8' \
--data-binary '{"bbox":[-82.99921369180083,42.56774741618392,-82.9694304428995,42.60749535184369],"query":{"collection":{"eq":"sentinel-2-l1c"}},"limit":1000}'
```
Response
```
{"type":"FeatureCollection","meta":{"page":1,"limit":1000,"found":12,"returned":12},"features":[{"type":"Feature","id":"S2A_17TLH_20190316_0", ... }]}
```

Other areas exhibiting this issue:

Alabama, USA (24 results dating back to January 18, 2019):
```
curl 'https://sat-api.developmentseed.org/stac/search' \
-H 'Content-Type: text/plain;charset=UTF-8' \
--data-binary '{"bbox":[-86.97843903210016,34.59868935397771,-86.97099321987481,34.60405869259581],"query":{"collection":{"eq":"sentinel-2-l1c"}},"limit":1000}'
```

South Australia, Australia (51 results dating back to January 12, 2019):
```
curl 'https://sat-api.developmentseed.org/stac/search' -H 'Content-Type: text/plain;charset=UTF-8' --data-binary '{"bbox":[138.99380922317508,-34.42236343038056,139.00870084762576,-34.41160096646385],"query":{"collection":{"eq":"sentinel-2-l1c"}},"limit":1000}'
```

Any idea what is causing these locations to be missing earlier Sentinel scenes?

Thanks for the great library!
Dan

**Comment by sharkinsspatial** [comment]
cc @matthewhanson Maybe we can sit down this upcoming week and try to investigate this?

**Comment by matthewhanson** [comment]
ah sorry @DanSchoppe I missed this. @sharkinsspatial yes definitely let's chat about this next week at FOSS4G-NA.

I suspect that this is because, at least in part, of orphaned Item files due to the problems we've had with maintaining a catalog of millions of files and async processing. A possible solution (and something we know and have talked about) is to use elasticsearch as the master copy. The code for sat-stac-sentinel should be updated to add the items directly to elasticsearch (at least as an option) rather than adding the items to the static catalog.

**Comment by lishrimp** [comment]
Just adding a few more data points for your info. All the following tiles should exist, but some exist and some don't. 

I'm looking forward to this issue to be resolved. :)

```
In [12]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160617_0']}).found()
Out[12]: 0

In [13]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_29QPD_20160713_0']}).found()
Out[13]: 1

In [14]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_41RMK_20160513_0']}).found()
Out[14]: 1

In [15]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_41SPS_20161020_0']}).found()
Out[15]: 1

In [16]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160617_0']}).found()
Out[16]: 0

In [17]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160617_1']}).found()
Out[17]: 0

In [18]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160617_0']}).found()
Out[18]: 0

In [19]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160624_0']}).found()
Out[19]: 0

In [20]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160627_0']}).found()
Out[20]: 0

In [21]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160525_0']}).found()
Out[21]: 0

In [22]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160515_0']}).found()
Out[22]: 0

In [23]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160329_0']}).found()
Out[23]: 0

In [24]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160218_0']}).found()
Out[24]: 0

In [25]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20160119_0']}).found()
Out[25]: 0

In [26]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190413_0']}).found()
Out[26]: 1

In [27]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190324_0']}).found()
Out[27]: 1

In [28]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_2019207_0']}).found()
Out[28]: 0

In [29]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190207_0']}).found()
Out[29]: 0

In [30]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190222_0']}).found()
Out[30]: 1

In [31]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190219_0']}).found()
Out[31]: 1

In [32]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190212_0']}).found()
Out[32]: 1

In [33]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20190123_0']}).found()
Out[33]: 1

In [34]: Search().search(**{'collection': 'sentinel-2-l1c', 'ids': ['S2A_34QFG_20181214_0']}).found()
Out[34]: 0
```

**Comment by matthewhanson** [comment]
STAC 0.7.0 is going to released in the coming days, which will be followed by updates to sat-api, and this also means that the catalogs will have to be updated.

We will be using a different approach to generating catalogs where we ingest directly into elasticsearch rather than trying to maintain a static catalog, which I think has caused many of the problems with missing scenes. 

No specific timeline for this, but we should see a more complete collection with sat-api 0.3.0.

**Comment by matthewhanson** [comment]
Closing this issue.   When there's a 0.7 release catalog feel free to open further issues in https://github.com/sat-utils/sat-stac-sentinel

**Comment by DanSchoppe** [comment]
@matthewhanson Thanks for the update! I see your new draft PR sat-utils/sat-api#190, so I'll follow that for news.

**Comment by gjones84** [comment]
Hi, I know this is closed, but hopefully this is the right place to ask - are there plans to update the API at sat-api.developmentseed.org to use sat-api 0.3.0, and if so, will this resolve this issue of missing images prior to Jan 2019?

**Comment by matthewhanson** [comment]
@gjones84  Not sure about the DevSeed API, but I am currently standing up a new API using the refactored and renamed [stac-api](https://github.com/stac-utils/stac-api), which will contain the complete archive of sentinel-1-l1c, sentinel-2-l1c, and sentinel-2-l2a.  Should be done by end of Feb.  Follow me on twitter for updates (@geoskeptic)

**Comment by gjones84** [comment]
Thanks heaps for that update @matthewhanson - really appreciate it. I'm following you now and very much looking forward to updates on the new API!
