### ISSUE TITLE
Switching to python docs shows both node and python

### ISSUE THREAD

**Issue by drewbo** [sat-utils/sat-api#171]
<img width="325" alt="Screen Shot 2019-03-22 at 8 22 42 AM" src="https://user-images.githubusercontent.com/7108211/54822604-ba316b00-4c7b-11e9-85bb-106164a5b47e.png">

**Comment by matthewhanson** [comment]
Any idea what is causing this @sharkinsspatial , easy fix?

**Comment by matthewhanson** [comment]
Not sure what is causing this, but for 0.3.0 we will be moving to redoc and this will be moot, see #181 , closing.
