### ISSUE TITLE
Migration from legacy to latest version

### ISSUE THREAD

**Issue by himanshu-sikaria** [sat-utils/sat-api#188]
Had built [rLandsat](https://github.com/atlanhq/rLandsat) a R library to search and download Landsat imagery. It has a dependency on sat-api. At the time of building of rLandsat we used the current `legacy` branch. 

1. Is the legacy still maintained and would it fetch the right/complete results?
2. What would be the equivalent of a  query like this in the new version? `https://api.developmentseed.org/satellites/?limit=10000&satellite_name=landsat-8&date_from=2018-07-01&date_to=2018-08-22&path=143&row=52`

**Comment by matthewhanson** [comment]
Hi @himanshu-sikaria , 

The legacy branch is not maintained, and is currently not capable of ingesting new scenes. I also don't think it's worth updating or maintaining, as the newer sat-api uses [STAC](https://github.com/radiantearth/stac-spec) as the metadata standard.

You can get examples of new queries by installing and using [sat-search](https://github.com/sat-utils/sat-search) which is a Python library, but also a Command Line Interface (CLI) tool allowing you to make queries against any STAC compliant API (it defaults to using https://sat-api.developmentseed.org).

If you use the CLI you can use the `-v` option to see the POST body that is provided to the API (note that sat-search does not use GET, although GET is supported), which will provide some help.

However, I must warn you that STAC is currently under development, and the API is one of the things that is most likely to change before a v1.0, so you may want to wait before updating rLandsat.

I do have an additional suggestion though.  sat-search is a useful library for users developing in Python, but for R it would be great to have an rSTAC library that works similarly to sat-search, but can be used for R developers. This would allow for more modular tools to be built in R around the STAC spec,.
