### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by j08lue** [sat-utils/sat-api#22]
Great API! But how do I call it? 

I went through most of the code and files but the only bit I found was [this](https://github.com/sat-utils/sat-api/blob/6db3b17931019653756a2b7e746338e6cd43253a/lambdas/api/index.js#L59-L67)

```javascript
 * @apiParam {Number} limit=1 Limit of results to return.
 * @apiParam {Number} skip=0 Results to skip in return.
 * @apiParam {Number} page=1 Results page to view.
 * @apiParam {String} fields Comma separated list of fields to include in the query results. Ex: `?fields=scene_id,date,cloud_coverage`.
 * @apiParam {String} contains Comma separated lists of form `longitude,latitude`. Returns results if the point  is within the bounding box of an image. Ex `?contains=40.23,70.76`.
 * @apiParam {String} intersects Valid GeoJSON, returns results that touch any point of the geometry.
 * @apiParam {String} scene_id Performs exact search on sceneID field.
 * @apiParam {Number} cloud_from The lower limit for cloud_coverage field.
 * @apiParam {Number} cloud_to The upper limit for cloud_coverage field.
```

Can anyone point me to some more information?

**Comment by j08lue** [comment]
OK, I found some examples in the `query_builder` function of [landsat-util](https://github.com/developmentseed/landsat-util/blob/188e2417035de197f1cae16a0200e4340236b4bb/landsat/search.py#L155)...

**Comment by j08lue** [comment]
And discovered that you can use glob-like wildcards with `scene_id`.

**Comment by drewbo** [comment]
@j08lue we have some documentation started at http://docs.sat-utils.org/ (based on the information you found above) but it could definitely use some more ❤️. Happy to answer any questions or accept PRs if you'd like to add anything.

**Comment by j08lue** [comment]
Thanks for the response, @drewbo !

I would love to add to the docs, but don't know how reliable the information is that I found by trial and error.

One perhaps important bit that I found is that you apparently can search for a specific satellite with `satellite_name:[sentinel-2a,landsat-8]`

But things I have not yet figured out are:
1. How do I do a date range query? `landsat-util` [suggests](https://github.com/developmentseed/landsat-util/blob/188e2417035de197f1cae16a0200e4340236b4bb/landsat/search.py#L273)
   https://api.developmentseed.org/satellites/?limit=100&search=acquisitionDate:2017-07-01+TO+2017-07-15
   but that also gives results outside the specified range. `date` does not work either.
2. How does the GeoJSON have to be formatted for the `intersects` parameter? This [does not work](https://api.developmentseed.org/satellites/?limit=100&search=intersects:{%22type%22:%22Polygon%22,%22coordinates%22:[[[7.745361328125,54.559322587438636],[15.238037109375,54.559322587438636],[15.238037109375,57.7920887227692],[7.745361328125,57.7920887227692],[7.745361328125,54.559322587438636]]]}):
```
{"type":"Polygon","coordinates":[[[7.745361328125,54.559322587438636],[15.238037109375,54.559322587438636],[15.238037109375,57.7920887227692],[7.745361328125,57.7920887227692],[7.745361328125,54.559322587438636]]]}
```
3. What are the satellite-specific parameters
   > Satellite specific parameters can be searched on the in the same fashion (exact match).
   are these the fields in the returned JSON, like `path` and `row` in the case of Landsat 8?

**Comment by drewbo** [comment]
@j08lue Thanks for the feedback and pushing on this. I've done a few things:
- Added notes about the documentation to this repo (the documentation is actually generated in https://github.com/sat-utils/sat-api-express/)
- Made the docs autogenerate on Circle-CI
- Added documentation about the date range filters (`date_to` and `date_from`)
- Added a better example of the filter matching for non-mentioned parameters (`path=30` for Landsat) but this could still be improved

I'm unsure about the `intersects` parameter failure but I'll look into it. Let me know if this solves your problems.

**Comment by j08lue** [comment]
Thanks @drewbo,

I think it might be very helpful to add some examples. That would have helped me a lot to get started:
* search globally for Sentinel 2 coverage for 1st of January 2017:
https://api.developmentseed.org/satellites/?limit=100&date_from=2017-01-01&date_to=2017-01-02&satellite_name=sentinel-2
* search for Sentinel 2 tile '32UMG' in January 2017:
https://api.developmentseed.org/satellites/?limit=100&date_from=2017-01-01&date_to=2017-01-31&search=scene_id:S2*201707*32UMG*

add some using the `intersects` keyword once we figured that out and and some examples for `landsat-8` using `path` and `row`, too, then most of the common use cases are covered.

**Comment by drewbo** [comment]
Agreed. I'm not sure we have an easy way to handle this currently as the [documentation generator](https://github.com/apidoc/apidoc) we're using doesn't seem to have support for adding these examples (though we could commit them to the html manually but that would interrupt the build/generation process). Let me know if you have any ideas how to implement

**Comment by j08lue** [comment]
The examples could probably go into the [`@apiDescription`](https://github.com/sat-utils/sat-api/blob/6db3b17931019653756a2b7e746338e6cd43253a/lambdas/api/index.js#L56-L57), but then they come in **above** the parameters table. If you don't like that, maybe just put it in the README of the repo and link to that to the `@apiDescription` (`"For examples, please consult the [README](https://github.com/sat-utils/sat-api/)"`).

**Comment by drewbo** [comment]
@j08lue I like the README idea; can you create a PR?
