### ISSUE TITLE
Sentinel-2 L2A

### ISSUE THREAD

**Issue by DanSchoppe** [sat-utils/sat-api#223]
👋 @matthewhanson ! Thanks for all of these great sat-utils tools!

I'm interested in making use of Sentinel-2 bottom-of-atmosphere ("L2A" aka "2A") imagery. From what I can tell, you've refactored https://github.com/sat-utils/sat-stac-sentinel to write STAC records directly to ElasticSearch as they become available, including Sentinel-2 L2A datasets 🎉.

Are you aware of any plans for sat-api.developmentseed.org to serve records from this new store? If not, is there any way to leverage a community-shared ElasticSearch database of these records (sort of like requester-pays S3 buckets) to avoid duplication of this infrastructure / effort?

If neither of these options are available, I'll be looking to use your `sat-stac-sentinel` (with inspiration from `sat-api-deployment`) to host a database + API from my own AWS account. I did notice the helpful SNS topics for newly processed STAC records, so that'll be a helpful resource.

Thanks again!
Dan

**Comment by matthewhanson** [comment]
Hi @DanSchoppe , thanks!

There are some ongoing efforts here.  As you saw, the stac-sentinel library now handles Sentinel-1 L1, and Sentinel-2 L1 and L2 data.  STAC metadata is generated for new scenes as they get added and published to a publicly available SNS topic, as given in the README.

I'm also currently deploying a new refactored version of sat-api (https://github.com/stac-utils/stac-api) to replace E84's Earth-Search: https://earth-search.aws.element84.com/stac 
It will include all of the S1 and S2 data in eu-central-1: i.e., collections `sentinel-s1-l1c`, `sentinel-s2-l1c`, and `sentinel-s2-l2a`.

In addition, I am also creating a mirror of the `sentinel-s2-l2a` data, but in COGs in us-west-2. This will also be indexed in the Earth-Search API, but as a different collection, called `sentinel-s2-l2a-cogs` or something similar.  This is going to be just for Africa right now, but there are some ongoing talks to get this expanded to be global.

**Comment by DanSchoppe** [comment]
@matthewhanson Thanks for all that you're doing on this and for the update! I saw your suggestion to watch your Twitter feed for updates, so I'll be doing so (@danschoppe on Twitter).

Is there any other way to engage with these projects, either element84's new STAC API or the L2A COGs in us-west-2? I'm working on a couple of projects that would benefit from both of these developments. Perhaps my company could be useful in expanding COG coverage outside of Africa as well.

**Comment by DanSchoppe** [comment]
@matthewhanson Please let me know if there are ways outsiders can help with either the `stac-api` on E84's Earth-Search or the COGing of Sentinel-2 L2A.

In the meantime I'm excited to hear any news you have to share! 😄

**Comment by DanSchoppe** [comment]
Closing!

https://www.element84.com/blog/sentinel-2-cloud-optimized-geotiffs-now-available-on-aws-registry-of-open-data
