### ISSUE TITLE
split: last lines of remoteCsv might not be processed

### ISSUE THREAD

**Issue by fredliporace** [sat-utils/sat-api#23]
Hello,

It seems that the the last remoteCSV lines are only processed when its count reaches linesPerFile (10000). That leaves up to 9999 lines not indexed - the most recent imagery in S2A case.

I made the following changes and it seems to be working, still testing to be sure that there is no impact on LS8 indexing - I tested only with S2A indexing up to now. I can include that change in a PR if you want.

rgds.

[patch.txt](https://github.com/sat-utils/sat-api/files/1235458/patch.txt)

**Comment by matthewhanson** [comment]
Thanks for the info in the patch @fredliporace I've included this fix in version 0.3.0
