### ISSUE TITLE
Sentinel 2 images for split tiles `sequence`

### ISSUE THREAD

**Issue by vincentsarago** [sat-utils/sat-api#26]
ref https://github.com/RemotePixel/satellitesearch/issues/5

Sometimes, Sentinel2 images are splited in two directories (**sequence**).

>[sequence] = e.g. 0 - in most cases there will be only one image per day. In case there are more (in northern latitudes), the following images will be 1,2,…\.

e.g.: 
```
aws s3 ls sentinel-s2-l1c/tiles/38/S/NG/2017/10/9/ --region eu-central-1
                           PRE 0/
                           PRE 1/
```

in 
https://github.com/sat-utils/sat-api/blob/26a73a864a8ac61f5bbb4ac0858a95ed973a0f64/lambdas/sentinel/index.js#L14-L16
the `version` is hardcoded with default to 0, and then not updated here https://github.com/sat-utils/sat-api/blob/26a73a864a8ac61f5bbb4ac0858a95ed973a0f64/lambdas/sentinel/index.js#L96

also set to **0** here https://github.com/sat-utils/sat-api/blob/26a73a864a8ac61f5bbb4ac0858a95ed973a0f64/lambdas/sentinel/index.js#L48

## Fix ?
I'm not sure how the database is feeded, so I'm not sure there is an easy fix here ?

cc @drewbo @scisco

**Comment by matthewhanson** [comment]
This is still an issue. I don't see where in the metadata (fed from a CSV file on Google Earth) this version is captured, I'm not sure how the version can be determined without getting file listings off s3. Any ideas @vincentsarago ?
```
GRANULE_ID,PRODUCT_ID,DATATAKE_IDENTIFIER,MGRS_TILE,SENSING_TIME,TOTAL_SIZE,CLOUD_COVER,GEOMETRIC_QUALITY_FLAG,GENERATION_TIME,NORTH_LAT,SOUTH_LAT,WEST_LON,EAST_LON,BASE_URL
L1C_T19FFB_A005055_20180223T140718,S2B_MSIL1C_20180223T140719_N0206_R024_T19FFB_20180223T201019,GS2B_20180223T140719_005055_N02.06,19FFB,2018-02-23T14:07:18.460000Z,190877712,99.0177,None,2018-02-23T20:10:19.000000Z,-52.895045195,-53.3274621275,-67.513621428,-65.8519866627,gs://gcp-public-data-sentinel-2/tiles/19/F/FB/S2B_MSIL1C_20180223T140719_N0206_R024_T19FFB_20180223T201019.SAFE
```

**Comment by vincentsarago** [comment]
I have absolutely no idea, might be worth asking Sinergise about that! @matthewhanson

**Comment by matthewhanson** [comment]
I'm actually not sure if this is still an issue or not. We now use the granule_id as the ID for the scene, and this should be unique. 

We need to check a case that has been split and see the granule ID in both cases and verify that they are in the API.

**Comment by matthewhanson** [comment]
We are moving to creating STAC flat file catalogs by crawling the bucket, so this won't be an issue anymore.
