### ISSUE TITLE
Google Cloud index link broken for older Landsat8 scenes (live version of API)

### ISSUE THREAD

**Issue by jirikadlec2** [sat-utils/sat-api#30]
I have noticed that the [google_index] has an incorrect link in some cases:
Example search for November 2013 L8 scenes from path=192, row=25 :
https://api.developmentseed.org/satellites/?limit=200&date_from=2013-11-01&date_to=2013-11-30&satellite_name=landsat-8&path=192&row=025
One scene is found with google_index:
https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/LC08/192/025/LC08_L1GT_192025_20131107_20170428_01_T2
But the correct google_index should be:
https://console.cloud.google.com/storage/browser/gcp-public-data-landsat/LC08/01/192/025/LC08_L1GT_192025_20131107_20170428_01_T2
NOTE the extra /01/ after /LC08/ in the URL.
The other links in the [download_links][google] are correct, only the google_index link is broken.

**Comment by matthewhanson** [comment]
Resolved in 0.3.0
