### ISSUE TITLE
Replace deployed sat-api with v0 API

### ISSUE THREAD

**Issue by matthewhanson** [sat-utils/sat-api#36]
The new API should replace the existing API with no compatibility changes, and should be specified as v0.

http://api.developmentseed.org/satellites/

**Comment by matthewhanson** [comment]
To close this issue:

- @drewbo to update libra to use eo:cloud_cover rather than cloudCoverFull
- Merge this PR: https://github.com/developmentseed/ds-nginx/pull/24 , which will point http://api.developmentseed.org/satellites to the new APIGateway endpoint.
- Delete CloudFormation stack sat-api-dev

**Comment by drewbo** [comment]
Libra is updated to use `cloud_coverage` (not `eo:cloud_coverage`) and deployed

**Comment by matthewhanson** [comment]
endpoint updated
stack "sat-api-dev" deleted
