### ISSUE TITLE
Empty search result for Sentinel-2 from March 2018

### ISSUE THREAD

**Issue by jirikadlec2** [sat-utils/sat-api#41]
Searching for Sentinel-2 images works OK until February 2018. But from March 2018 onwards, the search does not return any results although there are many images from that month available on Amazon AWS:

For example I issued a search request: 
https://api.developmentseed.org/satellites/?limit=200&date_from=2018-03-01&date_to=2018-03-22&satellite_name=sentinel-2&utm_zone=33&latitude_band=U&grid_square=VR

The search returns zero results although for tile 33UVR there are images available on AWS for example the image from 20th March 2018: 
http://sentinel-s2-l1c.s3.amazonaws.com/tiles/33/U/VR/2018/3/20/0/tileInfo.json

**Comment by matthewhanson** [comment]
@gakarak thanks for the update, I'll contact some folks at GEE and see about the index.

**Comment by matthewhanson** [comment]
This will no longer be an issue as we are moving to generating STAC format flat file records directly by crawling the bucket and reading metadata files.
