### ISSUE TITLE
Document how to make use of results paging

### ISSUE THREAD

**Issue by metasim** [sat-utils/sat-api#56]
When I submit a query to `sat-api`, part of the results is a summary of the total number of hits, and  what looks like a results paging capability:

```json
properties :{
    "found" : 6811 ,
    "limit" : 1 ,
    "page" : 1
}
```

I figured out that I can add query parameters to specify the per response limit and `page`:

    https://sat-api.developmentseed.org/search/stac?datetime=2017-08&limit=1&page=2

But I'm not sure what the semantics of `page` are: 

* total pages == `found`
* total pages == `found`/`limit`

Either way, docs on this would be helpful.

**Comment by matthewhanson** [comment]
@metasim Ah yes, there is little documentation currently, we're working on getting some proper API documentation up.

I'm not sure we are using the best terms here, and it may change depending on STAC API spec changes, but right now "limit" is essentially a page size. So "limit=100&page=1" will be the first 100 hits and "limit=100&page=2" will be the second 100 hits.  "found" is the total number of items matched.

Also, not sure if you've taken a look at sat-search, but if you are using python (or want a command line tool) you might find it helpful:
https://github.com/sat-utils/sat-search/

**Comment by metasim** [comment]
Thanks so much for the help @matthewhanson .... I'm querying this from Scala, trying to build a catalog DataSource for RasterFrames, so we can do this sort of thing:

```scala
val catalog = spark.read
  .format("stac")
  .load("https://sat-api.developmentseed.org/search/stac")
val scenes = catalog
  .select($"id", $"datetime", $"assets")
  .where($"datetime".between(Date.valueOf("2017-08-01"), Date.valueOf("2017-12-01")))
  .where($"geometry" intersects Point(-78.6445222907, 38.3957546898))

val tiles = scenes.select("$id", download_tiles($"assets"("B1")))
...
```

It's coming along, but eventually need to figure out what the appropriate query paging patterns are.

**Comment by metasim** [comment]
Also (I can file another issue if you like), the temporal search key according to the spec should be `time` and not `datetime`:

https://github.com/radiantearth/stac-spec/blob/f1971c4fc233de99623597fbd49e117c6e760748/api-spec/filters.md

**Comment by matthewhanson** [comment]
@metasim thanks for pointing that out, I think the STAC spec needs to be updated actually so that either the query term matches the field (datetime), or we have separate date and time filters (which I think may be better. I'll post an issue to discuss in the [stac repo](https://github.com/radiantearth/stac-spec)
