### ISSUE TITLE
Support for Landsat 8 L2

### ISSUE THREAD

**Issue by lucasvr** [sat-utils/sat-api#57]
Hi Matthew,

First of all, thanks for your outstanding work on sat-api and sat-search!

I've been using sat-search to obtain URLs to Landsat 8 scenes. It works like a charm, but it looks like the sat-api does not include support for Level 2 (bottom of atmosphere) scenes, hence searching for oe:platform=landsat-8-l2 does not work. If I'm not mistaken there was support for that with the old API, right?

Do you have plans to incorporate support for L2 on sat-api? If you do, but don't have a lot of time available to implement it right now, could you tell which data sources you were considering to use to retrieve that data?

**Comment by matthewhanson** [comment]
@lucasvr, thanks!  The Landsat-8 L2 data was not in the old sat-api, and is not currently on AWS. You have to currently get it through the USGS ordering process.
However, USGS is currently working on a new Analysis Ready Dataset (ARD), basically this is L2 data, and we are planning on adding that as soon as it's publicly available.

**Comment by lucasvr** [comment]
Ah, fair enough. That makes sense. I will keep an eye open on the announcements and on the project, then. Thanks!
