### ISSUE TITLE
Provide example of geospatial query string

### ISSUE THREAD

**Issue by metasim** [sat-utils/sat-api#63]
The README says

> No search term is more important however than the a geospatial query to find data covering a specific area. The core STAC spec allows for searching by providing a bounding box, with more complex 'intersects' query to query against user provided polygons. Sat-api does not currently support the [simpler] bounding box query, but does support the 'intersects' query.

doesn't give an example geospatial query like it does for the temporal queries. What would a `GET`-encoded query look like for, say, a bounding polygon?

**Comment by matthewhanson** [comment]
@metasim good point, we are working on redoing the documentation.

In the meantime, using sat-search with verbosity (e.g., -v 4), it will print out the complete URLs it is sending to sat-api.

**Comment by metasim** [comment]
Awesome tip! Will try that out.
