### ISSUE TITLE
Deployment instructions

### ISSUE THREAD

**Issue by fredliporace** [sat-utils/sat-api#69]
Hi,

I'm having some difficulties in following the documentation for deployments using the new structure.
The docs (deploy.md) mention the need to edit .kes/config.yml as in previous sat-api versions. I assumed initially that this was actually the example/.kes/config.yml directory, but this directory does not contain a cloudformation.template.yml file. It seems that the template is now under packages/api/template.

I may prepare a PR with the updated docs for deployment, but need an initial guidance on how to configure the kes environment.

I was able to execute the steps described in the "Building local version" section of the main readme.md, except the last one "yarn watch".

**Comment by fredliporace** [comment]
Is the right approach for deployment using the step defined in circleci configuration? I could start from there.

**Comment by fredliporace** [comment]
Just found out that updated deployment instructions are in example/README.md. Maybe deploy.md and references should be removed.

**Comment by matthewhanson** [comment]
sorry @fredliporace the docs got moved around, looking at your PR now.
