### ISSUE TITLE
Landsat 8 AWS URL

### ISSUE THREAD

**Issue by vincentsarago** [sat-utils/sat-api#7]
I think it will be nice to add the AWS URL for Landsat 8 images. 

I understand, all landsat data are not in AWS so updating the ES database will require two steps: 
- getting landsat8 csv from USGS
- getting scene list hosted on AWS

**Comment by scisco** [comment]
Very good point. I'll add it after implementing it here: https://github.com/sat-utils/sat-api-lib/issues/5

**Comment by vincentsarago** [comment]
Hi @scisco, 
Any news on this issue ?

Side note, it could be good to add the new AWS Landsat address `https://landsatonaws.com/L8/002/021/LC80020212016269LGN00` and also the thumbnail url use `https://landsat-pds.s3.amazonaws.com/L8/002/021/LC80020212016269LGN00/LC80020212016269LGN00_thumb_small.jpg` which is a true color thumbnail instead of the 654 from usgs.

**Comment by scisco** [comment]
@vincentsarago my only concern with switching to AWS thumbnails is that we still have to serve the old thumbnails for images from 2013,2014 which makes the thumbnails inconsistent. But I agree that TrueColor thumbnails are probably more useful.

@drewbo what do you think?

**Comment by drewbo** [comment]
I like the consistency of having 654 for all dates; also I think it is actually more broadly useful since the true color thumbnails are often dark while 654 tend to have consistent coloring. We should definitely add this as an alternate thumbnail at the very least.

**Comment by vincentsarago** [comment]
@drewbo @scisco good point.
I'm just trying to think about the users and to make consistency with the sentinel-2 previews.

If you just add the tag about image being on AWS, true preview url will be easy to create.

**Comment by scisco** [comment]
@vincentsarago agreed. will add

**Comment by vincentsarago** [comment]
@scisco 👍  thanks

**Comment by scisco** [comment]
Added
