### ISSUE TITLE
Missing (delay) in Landsat8 product ids

### ISSUE THREAD

**Issue by himanshu-sikaria** [sat-utils/sat-api#80]
I am running the following to get the latest product ids for the path 143 and row 52:
`https://api.developmentseed.org/satellites/?limit=10000&satellite_name=landsat-8&date_from=2018-07-01&date_to=2018-08-22&path=143&row=52`

The latest I get is the product id on 25th July 2018, even though the following product exists (10th August 2018), "LC08_L1TP_143052_20180810_20180815_01_T1"

Is there any delay or am I doing something wrong?

**Comment by matthewhanson** [comment]
Hello @himanshu-sikaria 
This is the API to the older version of the API, and there's been some changes recently with the metadata that is provided and that we use to ingest records. 

We can look into this when we get a chance, but if you are able to use the new version of sat-api we would recommend that. See the master branch.

**Comment by matthewhanson** [comment]
This has been corrected and the latest data is now ingested.
